# Generated by Django 5.1.4 on 2025-03-11 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.question')),
            ],
        ),
    ]
